//! AWK compatibility tests: runs every `tests/compat/cases/*.awk` program with both backends
//! and compares stdout and the exit code with the expected output generated by gawk
//! (see `tests/compat/regen.sh` for the case format).
//!
//! Cases listed in `tests/compat/known_failures.txt` are known differences from gawk: they are
//! still run, and the test fails if one of them starts passing, so the list stays accurate.
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

const BACKEND_ARGS: &[&str] = &["-Binterp", "-Bcranelift"];

fn compat_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests").join("compat")
}

fn directive<'a>(program: &'a str, name: &str) -> Option<&'a str> {
    let prefix = format!("# {}: ", name);
    program.lines().find_map(|line| line.strip_prefix(prefix.as_str()))
}

/// Known failures: case name => reason.
fn known_failures(dir: &Path) -> HashMap<String, String> {
    let text = fs::read_to_string(dir.join("known_failures.txt")).unwrap_or_default();
    text.lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| match line.split_once('#') {
            Some((name, reason)) => (name.trim().to_string(), reason.trim().to_string()),
            None => (line.to_string(), String::new()),
        })
        .collect()
}

/// Runs a case with the given backend, returns a description of the difference if any.
fn run_case(dir: &Path, awk_file: &Path, backend: &str) -> Option<String> {
    let program = fs::read_to_string(awk_file).unwrap();
    let expected = fs::read(awk_file.with_extension("out")).unwrap_or_else(|_| {
        panic!("missing expected output of {}, run tests/compat/regen.sh", awk_file.display())
    });
    let expected_code: i32 = directive(&program, "exit").map_or(0, |code| code.parse().unwrap());
    let split = |name| directive(&program, name).map_or(vec![], |s| s.split_whitespace().collect());
    let stdin = match directive(&program, "stdin") {
        Some(file) => Stdio::from(fs::File::open(dir.join(file)).unwrap()),
        None => Stdio::null(),
    };
    let output = Command::new(env!("CARGO_BIN_EXE_zawk"))
        .current_dir(dir)
        .env("LC_ALL", "C.UTF-8")
        .arg(backend)
        .args(split("opts"))
        .arg("-f")
        .arg(awk_file)
        .args(split("args"))
        .stdin(stdin)
        .output()
        .unwrap();
    let code = output.status.code().unwrap_or(-1);
    if output.stdout == expected && code == expected_code {
        return None;
    }
    Some(format!(
        "exit code: {} (expected {})\n--- expected\n{}--- actual\n{}{}",
        code,
        expected_code,
        String::from_utf8_lossy(&expected),
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    ))
}

#[test]
fn awk_compatibility() {
    let dir = compat_dir();
    let mut known = known_failures(&dir);
    let mut cases: Vec<PathBuf> = fs::read_dir(dir.join("cases"))
        .unwrap()
        .map(|entry| entry.unwrap().path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "awk"))
        .collect();
    cases.sort();
    assert!(!cases.is_empty(), "no compatibility test cases found");

    let mut errors = vec![];
    for awk_file in &cases {
        let name = awk_file.file_stem().unwrap().to_string_lossy().to_string();
        let failures: Vec<String> = BACKEND_ARGS
            .iter()
            .filter_map(|backend| run_case(&dir, awk_file, backend).map(|diff| format!("[{}] {}", backend, diff)))
            .collect();
        match (known.remove(&name).is_some(), failures.is_empty()) {
            (false, false) => errors.push(format!("FAIL {}\n{}", name, failures.join("\n"))),
            (true, true) => errors.push(format!(
                "PASS {}: listed in known_failures.txt but passes now, please remove it",
                name
            )),
            _ => {}
        }
    }
    for name in known.keys() {
        errors.push(format!("{}: listed in known_failures.txt but the case does not exist", name));
    }
    assert!(
        errors.is_empty(),
        "{} of {} compatibility cases differ from gawk:\n\n{}",
        errors.len(),
        cases.len(),
        errors.join("\n\n")
    );
}
